name: flutter_driver_helper
description: Utility for easy work with flutter_driver in UI / integration tests
version: 1.0.2
homepage: https://github.com/qwert2603/flutter_driver_helper

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  meta: ^1.1.8
  test: ^1.9.4
