name: flutter_driver_helper
description: Utility for easy work with flutter_driver in UI / integration tests
version: 2.0.0-alpha-0
homepage: https://github.com/qwert2603/flutter_driver_helper

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.3.0
